name: manage-azure-policy-6cf79b14
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'test1/policies/testingsiddhartan_9c6cdae5-ee3e-465e-b18e-e21da5082521/**'
#      - .github/workflows/manage-azure-policy-6cf79b14.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_6cf79b14}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          test1/policies/testingsiddhartan_9c6cdae5-ee3e-465e-b18e-e21da5082521/**
